#!/bin/sh
#  Bruxbot - backend/bruxbot-build
#  Copyright (C) 2023 hexaheximal
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# NOTE: You probably want to use bruxbotd, not this.
# TODO: implement musl support

set -e

BRUXBOT=${BRUXBOT:-$HOME/.bruxbot}
BRUX_REPOSITORY=${BRUX_REPOSITORY:-$(realpath ..)}
ORIGINAL_CWD=`pwd`
TARGET=${TARGET:-x86_64-linux-gnu}
FLAVOR=${FLAVOR:-generic}
BRUXBOT_TOOLCHAIN=${BRUXBOT}/toolchain/${TARGET}-${FLAVOR}

# attempt to figure out if the repository directory is valid

if [ -d ${BRUX_REPOSITORY}/.git ] && [ -d ${BRUX_REPOSITORY}/rte ]
then
	echo "Using repository: ${BRUX_REPOSITORY}" 
else
	echo "Please set the BRUX_REPOSITORY environment variable to a valid brux-gdk repository path."
fi

# make sure that the things we need exist

if [ ! -d ${BRUXBOT}/toolchain/${TARGET}-${FLAVOR} ]
then
	echo "Failed to find the toolchain directory. Please bootstrap it first!"
	exit 1
fi

echo "Using workdir: ${BRUXBOT}"

echo "Building brux-gdk..."

cd ${BRUX_REPOSITORY}/rte

if [ ! -d build-${TARGET}-${FLAVOR} ]
then
	mkdir build-${TARGET}-${FLAVOR}
fi

cd build-${TARGET}-${FLAVOR}

cmake -DCMAKE_TOOLCHAIN_FILE=${BRUXBOT_TOOLCHAIN}/toolchain.cmake ..
make -j$(nproc)

cd ${ORIGINAL_CWD}

echo "Finished!"
